name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Environment
      run: env
    - name: Checkout
      run: |
        if [ "$GITHUB_EVENT_NAME" == 'push' ]
        then
          git clone --recursive https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE && \
            git -C "$GITHUB_WORKSPACE" checkout $GITHUB_SHA
        elif [ "$GITHUB_EVENT_NAME" == 'pull_request' ]
        then
          git clone --single-branch --recursive https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE && \
            git -C "$GITHUB_WORKSPACE" fetch origin $GITHUB_REF && \
            git -C "$GITHUB_WORKSPACE" checkout FETCH_HEAD
        else
          git clone --recursive -b $GITHUB_HEAD_REF https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE
        fi
    - name: Setup Python 3.7
      run: |
        python_dir=$(ls -1d $RUNNER_TOOL_CACHE/Python/3.7*/x64 | tail -1)
        echo "${python_dir}" >> $GITHUB_PATH
        echo "${python_dir}/bin" >> $GITHUB_PATH
        echo "pythonLocation=${python_dir}" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install mysql_config on machine to avoid "OSError: mysql_config not found" error during pip install for mysqlclient.
        sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
        pip3 install -r deps/requirements.txt
        pip3 install -r deps/dev_requirements.txt
        pip3 install -r deps/vcs_requirements.txt
    - name: Run Python tests
      run: |
        ./tests/run_unit_tests.sh
